# Generated by Django 5.0.3 on 2024-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(default=0, unique=True)),
                ('role_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Roles',
                'ordering': ['-role_id'],
            },
        ),
        migrations.CreateModel(
            name='School_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('user_role', models.ManyToManyField(to='users.roles')),
            ],
            options={
                'verbose_name': 'Registered Members',
            },
        ),
    ]
