# Generated by Django 5.0.3 on 2024-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_school_users_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_users',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='School_User/user_profile_pictures/'),
        ),
    ]
