# Generated by Django 5.0.3 on 2024-03-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_school_users_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_users',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='School_User/user_profile_pictures/'),
        ),
        migrations.CreateModel(
            name='School_User_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school_users')),
            ],
            options={
                'verbose_name': 'Token For Registration',
            },
        ),
    ]
