# Generated by Django 5.0.3 on 2024-03-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_school_users_user_otp_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School_User_Token',
        ),
    ]
