# Generated by Django 5.0.3 on 2024-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_school_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('course_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('course_section', models.IntegerField(blank=True, default=0, null=True)),
                ('course_of', models.ManyToManyField(to='users.school_users')),
            ],
            options={
                'verbose_name': 'Courses',
            },
        ),
    ]
