# Generated by Django 5.0.3 on 2024-03-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_of',
            new_name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='users.school_users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assistant', to='users.school_users'),
            preserve_default=False,
        ),
    ]
