# Generated by Django 5.0.3 on 2024-03-23 11:52

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_course_of_course_students_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[500, 300], upload_to='Courses/<django.db.models.fields.CharField>/course_cover_picture/'),
        ),
    ]
