# Generated by Django 5.0.3 on 2024-03-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_instructor_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teaching_assistant',
        ),
    ]
