# Generated by Django 5.0.3 on 2024-03-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_course_instructor_remove_course_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school_users'),
        ),
        migrations.CreateModel(
            name='Teaching_Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('courses', models.ManyToManyField(to='users.course')),
                ('teaching_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school_users')),
            ],
            options={
                'verbose_name': 'Teaching Assistant Courses',
            },
        ),
    ]
