# Generated by Django 5.0.3 on 2024-03-25 06:22

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_course_course_section_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_users',
            name='user_profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='School_User/user_profile_pictures/'),
        ),
    ]
