# Generated by Django 5.0.3 on 2024-03-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_school_users_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='', max_length=50)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Session',
            },
        ),
    ]
