# Generated by Django 5.0.3 on 2024-03-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teaching_assistant',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.session'),
            preserve_default=False,
        ),
    ]
