# Generated by Django 5.0.3 on 2024-03-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_session_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
