# Generated by Django 5.0.3 on 2024-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_course_course_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_section',
            name='section_number',
            field=models.IntegerField(default=1),
        ),
    ]
