# Generated by Django 5.0.3 on 2024-03-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_course_section_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
