# Generated by Django 5.0.3 on 2024-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
