# Generated by Django 5.0.3 on 2024-03-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.RemoveField(
            model_name='teaching_assistant',
            name='year',
        ),
    ]
