# Generated by Django 5.0.3 on 2024-03-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_instructor_year_remove_student_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teaching_assistant',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
