# Generated by Django 5.0.3 on 2024-03-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_instructor_section_student_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_section',
            options={'ordering': ['-section_number'], 'verbose_name': 'Course Section'},
        ),
        migrations.AlterField(
            model_name='course_section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor'),
        ),
    ]
