# Generated by Django 5.0.3 on 2024-04-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_course_section_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_id', models.IntegerField(default=0)),
                ('mode', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Exam Mode',
            },
        ),
        migrations.CreateModel(
            name='Exam_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=0)),
                ('exam_type', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Exam Type',
            },
        ),
        migrations.CreateModel(
            name='Section_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.exam_mode')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.exam_type')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course_section')),
            ],
            options={
                'verbose_name': 'Section Exam',
            },
        ),
    ]
