# Generated by Django 5.0.3 on 2024-04-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_exam_mode_exam_type_section_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_exam',
            name='exam_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
