# Generated by Django 5.0.3 on 2024-04-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_section_exam_exam_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer_field_length', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.IntegerField(default=0)),
                ('questions_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section_exam')),
            ],
            options={
                'verbose_name': 'Questions',
            },
        ),
    ]
