# Generated by Django 5.0.3 on 2024-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_question_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_exam',
            name='ta_available',
            field=models.BooleanField(default=False),
        ),
    ]
