# Generated by Django 5.0.3 on 2024-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_section_exam_ta_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_field_length_number',
            field=models.IntegerField(default=0),
        ),
    ]
