# Generated by Django 5.0.3 on 2024-04-07 17:28

import django_resized.forms
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_question_answer_field_length_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[500, 300], upload_to=users.models.question_picture_upload_path),
        ),
    ]
