# Generated by Django 5.0.3 on 2024-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_exam',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
