# Generated by Django 5.0.3 on 2024-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_section_exam_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_exam',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
