# Generated by Django 5.0.3 on 2024-04-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_section_exam_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teaching_assistant',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_assistant',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
            preserve_default=False,
        ),
    ]
