# Generated by Django 5.0.3 on 2024-04-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_instructor_courses_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
        migrations.AlterField(
            model_name='teaching_assistant',
            name='courses',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
    ]
