# Generated by Django 5.0.3 on 2024-04-10 15:58

import django.db.models.deletion
import django_resized.forms
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_instructor_courses_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=1.0, size=[500, 300], upload_to=users.models.course_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=1.0, size=[500, 300], upload_to=users.models.question_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='school_users',
            name='user_profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=1.0, size=[1920, 1080], upload_to='School_User/user_profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_textfield', models.TextField(blank=True, null=True)),
                ('answer_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=1.0, size=[500, 300], upload_to=users.models.answer_picture_upload_path)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('answer_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.question')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school_users')),
            ],
            options={
                'verbose_name': 'Answers',
            },
        ),
    ]
