# Generated by Django 5.0.3 on 2024-04-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_course_course_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuffled_Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, default='A', max_length=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school_users')),
            ],
            options={
                'verbose_name': 'Shuffled Papers Student Info',
            },
        ),
    ]
