# Generated by Django 5.0.3 on 2024-04-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_shuffled_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_exam',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
