# Generated by Django 5.0.3 on 2024-04-12 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_section_exam_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuffled_papers',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course_section'),
        ),
    ]
