# Generated by Django 5.0.3 on 2024-04-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_shuffled_papers_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffled_papers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
