# Generated by Django 5.0.3 on 2024-04-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_shuffled_papers_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_exam',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
