# Generated by Django 5.0.3 on 2024-04-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_section_exam_is_stopped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.school_users'),
        ),
    ]
