# Generated by Django 5.0.3 on 2024-04-13 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_answer_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('exam_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.section_exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.school_users')),
            ],
            options={
                'verbose_name': 'Exam Submitted',
            },
        ),
    ]
