# Generated by Django 5.0.3 on 2024-04-13 12:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_exam_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_submitted',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.file_upload_path),
        ),
    ]
