# Generated by Django 5.0.3 on 2024-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_remove_exam_submitted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Exam_Submitted',
        ),
    ]
