# Generated by Django 5.0.3 on 2024-05-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_answer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
