# Generated by Django 5.0.3 on 2024-05-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_question_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.JSONField()),
                ('mid_score', models.JSONField()),
                ('final_score', models.IntegerField(blank=True, default=0, null=True)),
                ('exam_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section_exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school_users')),
            ],
            options={
                'verbose_name': 'Student Score',
            },
        ),
    ]
