# Generated by Django 5.0.3 on 2024-05-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_students_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_score',
            old_name='mid_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='students_score',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='students_score',
            name='quiz_score',
        ),
        migrations.AddField(
            model_name='students_score',
            name='exam_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.exam_type'),
            preserve_default=False,
        ),
    ]
