# Generated by Django 5.0.3 on 2024-05-10 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_students_score_total_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students_score',
            options={'ordering': ['-score'], 'verbose_name': 'Student Score'},
        ),
    ]
