# Generated by Django 5.0.3 on 2024-05-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_students_score_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students_score',
            options={'verbose_name': 'Student Score'},
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField(blank=True, null=True)),
                ('section_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.section_exam')),
            ],
            options={
                'verbose_name': 'Announcement',
            },
        ),
    ]
