# Generated by Django 5.0.3 on 2024-05-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_alter_students_score_options_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='given_by',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
