# Generated by Django 5.0.3 on 2024-05-22 08:40

import django_resized.forms
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_announcements_given_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, max_length=255, null=True, quality=90, scale=1.0, size=[500, 300], upload_to=users.models.answer_picture_upload_path),
        ),
    ]
