# Generated by Django 5.0.3 on 2024-05-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_answer_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuffled_papers',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.section_exam'),
            preserve_default=False,
        ),
    ]
