# Generated by Django 5.0.3 on 2024-05-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_shuffled_papers_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuffled_papers',
            name='exam',
        ),
    ]
