# Generated by Django 5.0.3 on 2024-05-30 18:14

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_remove_shuffled_papers_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.answer_picture_upload_path),
        ),
    ]
