# Generated by Django 5.0.3 on 2024-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System_Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('error_name', models.CharField(max_length=500)),
                ('error_occured_for', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(max_length=3000)),
                ('error_fix_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Errors',
            },
        ),
    ]
